#pragma once
enum {
    SYS_OPEN,
    SYS_WRITE,
    SYS_READ,
    SYS_IOCTL,
    SYS_MMAP,
    SYS_CLOSE,
    SYS_FORK,
    SYS_EXEC,
    SYS_EXIT,
    SYS_WAITPID,
    SYS_HEAP_CREATE,
    SYS_HEAP_ALLOCATE,
    SYS_HEAP_DEALLOCATE,
    SYS_CHDIR,
};
