#pragma once
#include <minos/keycodes.h>
enum {
    WM_KEY_LEFT_CTRL = MINOS_KEY_LEFT_CTRL,
    WM_KEY_RIGHT_CTL = MINOS_KEY_RIGHT_CTL,
    WM_KEY_LEFT_SHIFT = MINOS_KEY_LEFT_SHIFT,
    WM_KEY_RIGHT_SHIFT = MINOS_KEY_RIGHT_SHIFT,
    WM_KEY_LEFT_ALT = MINOS_KEY_LEFT_ALT,
    WM_KEY_RIGHT_ALT = MINOS_KEY_RIGHT_ALT,
    WM_KEY_CAPSLOCK = MINOS_KEY_CAPSLOCK,
    WM_KEY_SCROLLLOCK = MINOS_KEY_SCROLLLOCK,

    WM_KEY_NUMPAD_SLASH = MINOS_KEY_NUMPAD_SLASH,
    WM_KEY_NUMPAD_STAR = MINOS_KEY_NUMPAD_STAR,
    WM_KEY_NUMPAD_MINUS = MINOS_KEY_NUMPAD_MINUS,
    WM_KEY_NUMPAD_PLUS = MINOS_KEY_NUMPAD_PLUS,
    WM_KEY_NUMPAD_DOT = MINOS_KEY_NUMPAD_DOT,

    WM_KEY_NUMPAD_0 = MINOS_KEY_NUMPAD_0,
    WM_KEY_NUMPAD_1 = MINOS_KEY_NUMPAD_1,
    WM_KEY_NUMPAD_2 = MINOS_KEY_NUMPAD_2,
    WM_KEY_NUMPAD_3 = MINOS_KEY_NUMPAD_3,
    WM_KEY_NUMPAD_4 = MINOS_KEY_NUMPAD_4,
    WM_KEY_NUMPAD_5 = MINOS_KEY_NUMPAD_5,
    WM_KEY_NUMPAD_6 = MINOS_KEY_NUMPAD_6,
    WM_KEY_NUMPAD_7 = MINOS_KEY_NUMPAD_7,
    WM_KEY_NUMPAD_8 = MINOS_KEY_NUMPAD_8,
    WM_KEY_NUMPAD_9 = MINOS_KEY_NUMPAD_9,
    WM_KEY_NUMLOCK = MINOS_KEY_NUMLOCK,

    WM_KEY_F1 = MINOS_KEY_F1,
    WM_KEY_F2 = MINOS_KEY_F2,
    WM_KEY_F3 = MINOS_KEY_F3,
    WM_KEY_F4 = MINOS_KEY_F4,
    WM_KEY_F5 = MINOS_KEY_F5,
    WM_KEY_F6 = MINOS_KEY_F6,
    WM_KEY_F7 = MINOS_KEY_F7,
    WM_KEY_F8 = MINOS_KEY_F8,
    WM_KEY_F9 = MINOS_KEY_F9,
    WM_KEY_F10 = MINOS_KEY_F10,
    WM_KEY_F11 = MINOS_KEY_F11,
    WM_KEY_F12 = MINOS_KEY_F12,

    WM_KEY_UP_ARROW = MINOS_KEY_UP_ARROW,
    WM_KEY_DOWN_ARROW = MINOS_KEY_DOWN_ARROW,
    WM_KEY_RIGHT_ARROW = MINOS_KEY_RIGHT_ARROW,
    WM_KEY_LEFT_ARROW = MINOS_KEY_LEFT_ARROW,

    WM_KEY_COUNT
};
