#include "../../task.h"
#include <stdio.h>
#include <stddef.h>
int main(void) {
    printf("; Generated by " __FILE__ "\n"  
           "; DO NOT MODIFY\n");
    printf("TASK_cr3 equ %zu\n", offsetof(Task, cr3_phys));
    printf("TASK_rsp equ %zu\n", offsetof(Task, ts_rsp));
}
