#include <stdio.h>
#include <stdbool.h>

static bool exception_has_code[32] = {
    [8] = true,
    [10] = true,
    [11] = true,
    [12] = true,
    [13] = true,
    [14] = true,
    [17] = true,
    [21] = true,
    [29] = true,
    [30] = true,
};
int main(void) {
    printf("[BITS 64]\n"
           "; Generated by " __FILE__ ". Do not modify!\n"
           "section .text\n"
           "; Defined in C code\n"
           "extern irq_handle\n"
           "irq_base:\n"
           "    push rax\n"
           "    push rbx\n"
           "    push rcx\n"
           "    push rdx\n"
           "    push rsi\n"
           "    push rdi\n"
           "    push rbp\n"
           "    push r8\n"
           "    push r9\n"
           "    push r10\n"
           "    push r11\n"
           "    push r12\n"
           "    push r13\n"
           "    push r14\n"
           "    push r15\n"
           "    mov rdi, rsp\n"
           "    call irq_handle\n"
           "    pop r15\n"
           "    pop r14\n"
           "    pop r13\n"
           "    pop r12\n"
           "    pop r11\n"
           "    pop r10\n"
           "    pop r9\n"
           "    pop r8\n"
           "    pop rbp\n"
           "    pop rdi\n"
           "    pop rsi\n"
           "    pop rdx\n"
           "    pop rcx\n"
           "    pop rbx\n"
           "    pop rax\n"
           "    add rsp, 8\n"
           "    iretq\n"

           "irq_base_exception:\n"
           "    push rax\n"
           "    push rbx\n"
           "    push rcx\n"
           "    push rdx\n"
           "    push rsi\n"
           "    push rdi\n"
           "    push rbp\n"
           "    push r8\n"
           "    push r9\n"
           "    push r10\n"
           "    push r11\n"
           "    push r12\n"
           "    push r13\n"
           "    push r14\n"
           "    push r15\n"
           "    mov rdi, rsp\n"
           "    call irq_handle\n"
           "    pop r15\n"
           "    pop r14\n"
           "    pop r13\n"
           "    pop r12\n"
           "    pop r11\n"
           "    pop r10\n"
           "    pop r9\n"
           "    pop r8\n"
           "    pop rbp\n"
           "    pop rdi\n"
           "    pop rsi\n"
           "    pop rdx\n"
           "    pop rcx\n"
           "    pop rbx\n"
           "    pop rax\n"
           "    add rsp, 16\n"
           "    iretq\n"
        );

    size_t exception_start = 0, exception_end = 32;
    size_t start_irq = 32, end_irq = 255;
    size_t spurious_irq = 255;

    printf("; Exceptions irq %zu -> %zu\n", exception_start, exception_end - 1);
    for(size_t i = exception_start; i < exception_end; ++i) {
        printf("global _irq_%zu\n", i);
        printf("_irq_%zu:\n", i);
        if(!exception_has_code[i]) {
            printf("    push 0\n");
        }
        printf("    push %zu\n"
               "    jmp irq_base_exception\n"
            , i);
    }
    printf("; General purpose irq %zu -> %zu\n", start_irq, end_irq - 1);
    for(size_t i = start_irq; i < end_irq; ++i) {
        printf("global _irq_%zu\n", i);
        printf("_irq_%zu:\n"
               "    push %zu\n"
               "    jmp irq_base\n"
            , i, i);
    }
    // Spurious is completely ignored
    printf("; Spurious interrupt irq %zu\n"
           "_irq_%zu:\n"
           "    iretq\n"
        , spurious_irq, spurious_irq);
    printf("section .data\n"
           "global _irq_vectors\n"
           "_irq_vectors:\n");
    for(size_t i = 0; i < 256; ++i) {
        printf("    dq _irq_%zu\n", i);
    }
}
