#pragma once
#include "utils.h"
// TODO: Better usage of the key fields and bits
enum {
   MINOS_KEY_ENTER=256, // <256 are mostly ASCII keycodes
   MINOS_KEY_BACKSPACE,
   MINOS_KEY_TAB,
   MINOS_KEY_ESCAPE,
   MINOS_KEY_LEFT_CTRL,
   MINOS_KEY_LEFT_SHIFT,
   MINOS_KEY_RIGHT_SHIFT,
   MINOS_KEY_LEFT_ALT,
   MINOS_KEY_CAPSLOCK,
   MINOS_KEY_SCROLLLOCK,

   MINOS_KEY_NUMPAD_SLASH,
   MINOS_KEY_NUMPAD_STAR,
   MINOS_KEY_NUMPAD_MINUS,
   MINOS_KEY_NUMPAD_PLUS,
   MINOS_KEY_NUMPAD_DOT,

   MINOS_KEY_NUMPAD_0,
   MINOS_KEY_NUMPAD_1,
   MINOS_KEY_NUMPAD_2,
   MINOS_KEY_NUMPAD_3,
   MINOS_KEY_NUMPAD_4,
   MINOS_KEY_NUMPAD_5,
   MINOS_KEY_NUMPAD_6,
   MINOS_KEY_NUMPAD_7,
   MINOS_KEY_NUMPAD_8,
   MINOS_KEY_NUMPAD_9,
   MINOS_KEY_NUMLOCK,

   MINOS_KEY_F1,
   MINOS_KEY_F2,
   MINOS_KEY_F3,
   MINOS_KEY_F4,
   MINOS_KEY_F5,
   MINOS_KEY_F6,
   MINOS_KEY_F7,
   MINOS_KEY_F8,
   MINOS_KEY_F9,
   MINOS_KEY_F10,
   MINOS_KEY_F11,
   MINOS_KEY_F12,

   MINOS_KEY_COUNT
};
