#include "msi.h"
#include <log.h>
#include <interrupt.h>
#include <minos/status.h>
static intptr_t msi_reserve_irq(MSIManager* m) {
    for(size_t i = 0; i < sizeof(m->irqs); ++i) {
        if(m->irqs[i] == 0xFF) continue;
        size_t j = 0;
        while(m->irqs[i] & (1 << j)) j++;
        m->irqs[i] |= 1<<j;
        return (i * 8 + j);
    }
    return -LIMITS;
}
intptr_t msi_register(MSIManager* m, PciDevice* dev) {
    intptr_t e;
    if((e=msi_reserve_irq(m)) < 0) return e;
    uint8_t msi = e;
    if((e=irq_register(dev->irq = (MSI_BASE + msi), msi_handlers[msi], 0)) < 0) return e;
    m->pci_devices[msi] = dev;
    uint8_t vec = e;
    pci_device_msi_set(dev, MSI_ADDRESS, vec);
    // NOTE: If its a problem in the future. Move this out
    pci_device_msi_enable(dev);
    return 0;
}
MSIManager msi_manager={0};
// Automatically generated by msi_dispatcher.c (Not included in repo)
#define MSI_LIST \
    X(0) \
    X(1) \
    X(2) \
    X(3) \
    X(4) \
    X(5) \
    X(6) \
    X(7) \
    X(8) \
    X(9) \
    X(10) \
    X(11) \
    X(12) \
    X(13) \
    X(14) \
    X(15) \
    X(16) \
    X(17) \
    X(18) \
    X(19) \
    X(20) \
    X(21) \
    X(22) \
    X(23) \
    X(24) \
    X(25) \
    X(26) \
    X(27) \
    X(28) \
    X(29) \
    X(30) \
    X(31) \
    X(32) \
    X(33) \
    X(34) \
    X(35) \
    X(36) \
    X(37) \
    X(38) \
    X(39) \
    X(40) \
    X(41) \
    X(42) \
    X(43) \
    X(44) \
    X(45) \
    X(46) \
    X(47)
#define X(n) extern void msi_irq_##n(void);
MSI_LIST;
#undef X
#define X(n) msi_irq_##n ,
msi_handler_t msi_handlers[MSI_COUNT] = {
    MSI_LIST
};
#undef X
