#pragma once
#define USER_STACK_PAGES      6
#define USER_STACK_ADDR       (USER_STACK_PTR - USER_STACK_PAGES*PAGE_SIZE)
#define USER_STACK_PTR        0x700000000000
#define REGION_HHDM_ADDR      0xFFFF800000000000LL
#define REGION_HHDM_PAGES     1048576
#define KERNEL_STACK_PAGES    10LL
#define KERNEL_STACK_ADDR     (-(KERNEL_STACK_PAGES*PAGE_SIZE))
#define KERNEL_STACK_PTR      0xFFFFFFFFFFFFF000LL
#define KERNEL_MEMORY_MASK    REGION_HHDM_ADDR

